// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package so.service1;

/**
 * Protobuf type {@code service1.AirQualResponse}
 */
public  final class AirQualResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:service1.AirQualResponse)
    AirQualResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AirQualResponse.newBuilder() to construct.
  private AirQualResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AirQualResponse() {
    currentAirQuality_ = 0;
    newVentilationLevel_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AirQualResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            currentAirQuality_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            newVentilationLevel_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return so.service1.Service1Impl.internal_static_service1_AirQualResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return so.service1.Service1Impl.internal_static_service1_AirQualResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            so.service1.AirQualResponse.class, so.service1.AirQualResponse.Builder.class);
  }

  public static final int CURRENTAIRQUALITY_FIELD_NUMBER = 1;
  private int currentAirQuality_;
  /**
   * <code>int32 currentAirQuality = 1;</code>
   */
  public int getCurrentAirQuality() {
    return currentAirQuality_;
  }

  public static final int NEWVENTILATIONLEVEL_FIELD_NUMBER = 2;
  private volatile java.lang.Object newVentilationLevel_;
  /**
   * <pre>
   *Confirming the newly set office ventilation level
   * </pre>
   *
   * <code>string newVentilationLevel = 2;</code>
   */
  public java.lang.String getNewVentilationLevel() {
    java.lang.Object ref = newVentilationLevel_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      newVentilationLevel_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *Confirming the newly set office ventilation level
   * </pre>
   *
   * <code>string newVentilationLevel = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNewVentilationLevelBytes() {
    java.lang.Object ref = newVentilationLevel_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      newVentilationLevel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (currentAirQuality_ != 0) {
      output.writeInt32(1, currentAirQuality_);
    }
    if (!getNewVentilationLevelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, newVentilationLevel_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (currentAirQuality_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, currentAirQuality_);
    }
    if (!getNewVentilationLevelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, newVentilationLevel_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof so.service1.AirQualResponse)) {
      return super.equals(obj);
    }
    so.service1.AirQualResponse other = (so.service1.AirQualResponse) obj;

    boolean result = true;
    result = result && (getCurrentAirQuality()
        == other.getCurrentAirQuality());
    result = result && getNewVentilationLevel()
        .equals(other.getNewVentilationLevel());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CURRENTAIRQUALITY_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentAirQuality();
    hash = (37 * hash) + NEWVENTILATIONLEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getNewVentilationLevel().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static so.service1.AirQualResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static so.service1.AirQualResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static so.service1.AirQualResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static so.service1.AirQualResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static so.service1.AirQualResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static so.service1.AirQualResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static so.service1.AirQualResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static so.service1.AirQualResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static so.service1.AirQualResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static so.service1.AirQualResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static so.service1.AirQualResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static so.service1.AirQualResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(so.service1.AirQualResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code service1.AirQualResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:service1.AirQualResponse)
      so.service1.AirQualResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return so.service1.Service1Impl.internal_static_service1_AirQualResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return so.service1.Service1Impl.internal_static_service1_AirQualResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              so.service1.AirQualResponse.class, so.service1.AirQualResponse.Builder.class);
    }

    // Construct using so.service1.AirQualResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      currentAirQuality_ = 0;

      newVentilationLevel_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return so.service1.Service1Impl.internal_static_service1_AirQualResponse_descriptor;
    }

    @java.lang.Override
    public so.service1.AirQualResponse getDefaultInstanceForType() {
      return so.service1.AirQualResponse.getDefaultInstance();
    }

    @java.lang.Override
    public so.service1.AirQualResponse build() {
      so.service1.AirQualResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public so.service1.AirQualResponse buildPartial() {
      so.service1.AirQualResponse result = new so.service1.AirQualResponse(this);
      result.currentAirQuality_ = currentAirQuality_;
      result.newVentilationLevel_ = newVentilationLevel_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof so.service1.AirQualResponse) {
        return mergeFrom((so.service1.AirQualResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(so.service1.AirQualResponse other) {
      if (other == so.service1.AirQualResponse.getDefaultInstance()) return this;
      if (other.getCurrentAirQuality() != 0) {
        setCurrentAirQuality(other.getCurrentAirQuality());
      }
      if (!other.getNewVentilationLevel().isEmpty()) {
        newVentilationLevel_ = other.newVentilationLevel_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      so.service1.AirQualResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (so.service1.AirQualResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int currentAirQuality_ ;
    /**
     * <code>int32 currentAirQuality = 1;</code>
     */
    public int getCurrentAirQuality() {
      return currentAirQuality_;
    }
    /**
     * <code>int32 currentAirQuality = 1;</code>
     */
    public Builder setCurrentAirQuality(int value) {
      
      currentAirQuality_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 currentAirQuality = 1;</code>
     */
    public Builder clearCurrentAirQuality() {
      
      currentAirQuality_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object newVentilationLevel_ = "";
    /**
     * <pre>
     *Confirming the newly set office ventilation level
     * </pre>
     *
     * <code>string newVentilationLevel = 2;</code>
     */
    public java.lang.String getNewVentilationLevel() {
      java.lang.Object ref = newVentilationLevel_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        newVentilationLevel_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *Confirming the newly set office ventilation level
     * </pre>
     *
     * <code>string newVentilationLevel = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNewVentilationLevelBytes() {
      java.lang.Object ref = newVentilationLevel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        newVentilationLevel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *Confirming the newly set office ventilation level
     * </pre>
     *
     * <code>string newVentilationLevel = 2;</code>
     */
    public Builder setNewVentilationLevel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      newVentilationLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Confirming the newly set office ventilation level
     * </pre>
     *
     * <code>string newVentilationLevel = 2;</code>
     */
    public Builder clearNewVentilationLevel() {
      
      newVentilationLevel_ = getDefaultInstance().getNewVentilationLevel();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Confirming the newly set office ventilation level
     * </pre>
     *
     * <code>string newVentilationLevel = 2;</code>
     */
    public Builder setNewVentilationLevelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      newVentilationLevel_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:service1.AirQualResponse)
  }

  // @@protoc_insertion_point(class_scope:service1.AirQualResponse)
  private static final so.service1.AirQualResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new so.service1.AirQualResponse();
  }

  public static so.service1.AirQualResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AirQualResponse>
      PARSER = new com.google.protobuf.AbstractParser<AirQualResponse>() {
    @java.lang.Override
    public AirQualResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AirQualResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AirQualResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AirQualResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public so.service1.AirQualResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

