// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package so.service1;

public interface AirQualResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.AirQualResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 currentAirQuality = 1;</code>
   */
  int getCurrentAirQuality();

  /**
   * <pre>
   *Confirming the newly set office ventilation level
   * </pre>
   *
   * <code>string newVentilationLevel = 2;</code>
   */
  java.lang.String getNewVentilationLevel();
  /**
   * <pre>
   *Confirming the newly set office ventilation level
   * </pre>
   *
   * <code>string newVentilationLevel = 2;</code>
   */
  com.google.protobuf.ByteString
      getNewVentilationLevelBytes();
}
