// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package so.service1;

public interface AirQualRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.AirQualRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string operationType = 1;</code>
   */
  java.lang.String getOperationType();
  /**
   * <code>string operationType = 1;</code>
   */
  com.google.protobuf.ByteString
      getOperationTypeBytes();

  /**
   * <pre>
   *Used for SetAirQual
   * </pre>
   *
   * <code>int32 ventilationLevel = 2;</code>
   */
  int getVentilationLevel();
}
