// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package so.service1;

public interface LightingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.LightingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *Used for lighting level
   * </pre>
   *
   * <code>int32 lightingLevel = 1;</code>
   */
  int getLightingLevel();
}
