// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package so.service1;

public interface LightingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.LightingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *Confirming the newly set office lighting level
   * </pre>
   *
   * <code>string newLightingLevel = 1;</code>
   */
  java.lang.String getNewLightingLevel();
  /**
   * <pre>
   *Confirming the newly set office lighting level
   * </pre>
   *
   * <code>string newLightingLevel = 1;</code>
   */
  com.google.protobuf.ByteString
      getNewLightingLevelBytes();
}
