// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package so.service1;

public final class Service1Impl {
  private Service1Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_AirQualRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_AirQualRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_AirQualResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_AirQualResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_TempRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_TempRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_TempResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_TempResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_LightingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_LightingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_LightingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_LightingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service1.proto\022\010service1\"A\n\016AirQualReq" +
      "uest\022\025\n\roperationType\030\001 \001(\t\022\030\n\020ventilati" +
      "onLevel\030\002 \001(\005\"I\n\017AirQualResponse\022\031\n\021curr" +
      "entAirQuality\030\001 \001(\005\022\033\n\023newVentilationLev" +
      "el\030\002 \001(\t\"7\n\013TempRequest\022\025\n\roperationType" +
      "\030\001 \001(\t\022\021\n\ttempLevel\030\002 \001(\002\"9\n\014TempRespons" +
      "e\022\023\n\013currentTemp\030\001 \001(\002\022\024\n\014newTempLevel\030\002" +
      " \001(\t\"(\n\017LightingRequest\022\025\n\rlightingLevel" +
      "\030\001 \001(\005\",\n\020LightingResponse\022\030\n\020newLightin" +
      "gLevel\030\001 \001(\t2\231\001\n\021AirQualityControl\022A\n\nSe" +
      "tAirQual\022\030.service1.AirQualRequest\032\031.ser" +
      "vice1.AirQualResponse\022A\n\nGetAirQual\022\030.se" +
      "rvice1.AirQualRequest\032\031.service1.AirQual" +
      "Response2\201\001\n\013TempControl\0228\n\007SetTemp\022\025.se" +
      "rvice1.TempRequest\032\026.service1.TempRespon" +
      "se\0228\n\007GetTemp\022\025.service1.TempRequest\032\026.s" +
      "ervice1.TempResponse2W\n\017LightingControl\022" +
      "D\n\013SetLighting\022\031.service1.LightingReques" +
      "t\032\032.service1.LightingResponseB\035\n\013so.serv" +
      "ice1B\014Service1ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service1_AirQualRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service1_AirQualRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_AirQualRequest_descriptor,
        new java.lang.String[] { "OperationType", "VentilationLevel", });
    internal_static_service1_AirQualResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service1_AirQualResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_AirQualResponse_descriptor,
        new java.lang.String[] { "CurrentAirQuality", "NewVentilationLevel", });
    internal_static_service1_TempRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service1_TempRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_TempRequest_descriptor,
        new java.lang.String[] { "OperationType", "TempLevel", });
    internal_static_service1_TempResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service1_TempResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_TempResponse_descriptor,
        new java.lang.String[] { "CurrentTemp", "NewTempLevel", });
    internal_static_service1_LightingRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_service1_LightingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_LightingRequest_descriptor,
        new java.lang.String[] { "LightingLevel", });
    internal_static_service1_LightingResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_service1_LightingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_LightingResponse_descriptor,
        new java.lang.String[] { "NewLightingLevel", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
