// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package so.service1;

public interface TempResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.TempResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *Current Office Temp
   * </pre>
   *
   * <code>float currentTemp = 1;</code>
   */
  float getCurrentTemp();

  /**
   * <pre>
   *Confirming the newly set office temperature
   * </pre>
   *
   * <code>string newTempLevel = 2;</code>
   */
  java.lang.String getNewTempLevel();
  /**
   * <pre>
   *Confirming the newly set office temperature
   * </pre>
   *
   * <code>string newTempLevel = 2;</code>
   */
  com.google.protobuf.ByteString
      getNewTempLevelBytes();
}
