// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package so.service1;

public interface TempRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.TempRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string operationType = 1;</code>
   */
  java.lang.String getOperationType();
  /**
   * <code>string operationType = 1;</code>
   */
  com.google.protobuf.ByteString
      getOperationTypeBytes();

  /**
   * <pre>
   *Used for SetTemp
   * </pre>
   *
   * <code>float tempLevel = 2;</code>
   */
  float getTempLevel();
}
