// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package so.service3;

public interface AddContentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.AddContentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *Name of the whiteboard content to be added
   * </pre>
   *
   * <code>string whiteboardName = 1;</code>
   */
  java.lang.String getWhiteboardName();
  /**
   * <pre>
   *Name of the whiteboard content to be added
   * </pre>
   *
   * <code>string whiteboardName = 1;</code>
   */
  com.google.protobuf.ByteString
      getWhiteboardNameBytes();

  /**
   * <pre>
   *Add content to whiteboard
   * </pre>
   *
   * <code>string addContent = 2;</code>
   */
  java.lang.String getAddContent();
  /**
   * <pre>
   *Add content to whiteboard
   * </pre>
   *
   * <code>string addContent = 2;</code>
   */
  com.google.protobuf.ByteString
      getAddContentBytes();
}
