// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package so.service3;

public interface AddContentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.AddContentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *Confirmation that new content was added
   * </pre>
   *
   * <code>string newWhiteboardContent = 1;</code>
   */
  java.lang.String getNewWhiteboardContent();
  /**
   * <pre>
   *Confirmation that new content was added
   * </pre>
   *
   * <code>string newWhiteboardContent = 1;</code>
   */
  com.google.protobuf.ByteString
      getNewWhiteboardContentBytes();
}
