// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package so.service3;

public interface CreateWhiteboardResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.CreateWhiteboardResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *Confirmation of the title beign set
   * </pre>
   *
   * <code>string whiteboardName = 1;</code>
   */
  java.lang.String getWhiteboardName();
  /**
   * <pre>
   *Confirmation of the title beign set
   * </pre>
   *
   * <code>string whiteboardName = 1;</code>
   */
  com.google.protobuf.ByteString
      getWhiteboardNameBytes();
}
