// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package so.service3;

public interface CreateWhiteboardRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.CreateWhiteboardRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *Give the whiteboard a title
   * </pre>
   *
   * <code>string newWhiteboard = 1;</code>
   */
  java.lang.String getNewWhiteboard();
  /**
   * <pre>
   *Give the whiteboard a title
   * </pre>
   *
   * <code>string newWhiteboard = 1;</code>
   */
  com.google.protobuf.ByteString
      getNewWhiteboardBytes();
}
