// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package so.service3;

/**
 * Protobuf type {@code service3.CreateWhiteboardResponse}
 */
public  final class CreateWhiteboardResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:service3.CreateWhiteboardResponse)
    CreateWhiteboardResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateWhiteboardResponse.newBuilder() to construct.
  private CreateWhiteboardResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateWhiteboardResponse() {
    whiteboardName_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateWhiteboardResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            whiteboardName_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return so.service3.Service3Impl.internal_static_service3_CreateWhiteboardResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return so.service3.Service3Impl.internal_static_service3_CreateWhiteboardResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            so.service3.CreateWhiteboardResponse.class, so.service3.CreateWhiteboardResponse.Builder.class);
  }

  public static final int WHITEBOARDNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object whiteboardName_;
  /**
   * <pre>
   *Confirmation of the title beign set
   * </pre>
   *
   * <code>string whiteboardName = 1;</code>
   */
  public java.lang.String getWhiteboardName() {
    java.lang.Object ref = whiteboardName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      whiteboardName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *Confirmation of the title beign set
   * </pre>
   *
   * <code>string whiteboardName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getWhiteboardNameBytes() {
    java.lang.Object ref = whiteboardName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      whiteboardName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getWhiteboardNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, whiteboardName_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getWhiteboardNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, whiteboardName_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof so.service3.CreateWhiteboardResponse)) {
      return super.equals(obj);
    }
    so.service3.CreateWhiteboardResponse other = (so.service3.CreateWhiteboardResponse) obj;

    boolean result = true;
    result = result && getWhiteboardName()
        .equals(other.getWhiteboardName());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WHITEBOARDNAME_FIELD_NUMBER;
    hash = (53 * hash) + getWhiteboardName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static so.service3.CreateWhiteboardResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static so.service3.CreateWhiteboardResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static so.service3.CreateWhiteboardResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static so.service3.CreateWhiteboardResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static so.service3.CreateWhiteboardResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static so.service3.CreateWhiteboardResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static so.service3.CreateWhiteboardResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static so.service3.CreateWhiteboardResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static so.service3.CreateWhiteboardResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static so.service3.CreateWhiteboardResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static so.service3.CreateWhiteboardResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static so.service3.CreateWhiteboardResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(so.service3.CreateWhiteboardResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code service3.CreateWhiteboardResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:service3.CreateWhiteboardResponse)
      so.service3.CreateWhiteboardResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return so.service3.Service3Impl.internal_static_service3_CreateWhiteboardResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return so.service3.Service3Impl.internal_static_service3_CreateWhiteboardResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              so.service3.CreateWhiteboardResponse.class, so.service3.CreateWhiteboardResponse.Builder.class);
    }

    // Construct using so.service3.CreateWhiteboardResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      whiteboardName_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return so.service3.Service3Impl.internal_static_service3_CreateWhiteboardResponse_descriptor;
    }

    @java.lang.Override
    public so.service3.CreateWhiteboardResponse getDefaultInstanceForType() {
      return so.service3.CreateWhiteboardResponse.getDefaultInstance();
    }

    @java.lang.Override
    public so.service3.CreateWhiteboardResponse build() {
      so.service3.CreateWhiteboardResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public so.service3.CreateWhiteboardResponse buildPartial() {
      so.service3.CreateWhiteboardResponse result = new so.service3.CreateWhiteboardResponse(this);
      result.whiteboardName_ = whiteboardName_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof so.service3.CreateWhiteboardResponse) {
        return mergeFrom((so.service3.CreateWhiteboardResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(so.service3.CreateWhiteboardResponse other) {
      if (other == so.service3.CreateWhiteboardResponse.getDefaultInstance()) return this;
      if (!other.getWhiteboardName().isEmpty()) {
        whiteboardName_ = other.whiteboardName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      so.service3.CreateWhiteboardResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (so.service3.CreateWhiteboardResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object whiteboardName_ = "";
    /**
     * <pre>
     *Confirmation of the title beign set
     * </pre>
     *
     * <code>string whiteboardName = 1;</code>
     */
    public java.lang.String getWhiteboardName() {
      java.lang.Object ref = whiteboardName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        whiteboardName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *Confirmation of the title beign set
     * </pre>
     *
     * <code>string whiteboardName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWhiteboardNameBytes() {
      java.lang.Object ref = whiteboardName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        whiteboardName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *Confirmation of the title beign set
     * </pre>
     *
     * <code>string whiteboardName = 1;</code>
     */
    public Builder setWhiteboardName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      whiteboardName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Confirmation of the title beign set
     * </pre>
     *
     * <code>string whiteboardName = 1;</code>
     */
    public Builder clearWhiteboardName() {
      
      whiteboardName_ = getDefaultInstance().getWhiteboardName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Confirmation of the title beign set
     * </pre>
     *
     * <code>string whiteboardName = 1;</code>
     */
    public Builder setWhiteboardNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      whiteboardName_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:service3.CreateWhiteboardResponse)
  }

  // @@protoc_insertion_point(class_scope:service3.CreateWhiteboardResponse)
  private static final so.service3.CreateWhiteboardResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new so.service3.CreateWhiteboardResponse();
  }

  public static so.service3.CreateWhiteboardResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateWhiteboardResponse>
      PARSER = new com.google.protobuf.AbstractParser<CreateWhiteboardResponse>() {
    @java.lang.Override
    public CreateWhiteboardResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateWhiteboardResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateWhiteboardResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateWhiteboardResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public so.service3.CreateWhiteboardResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

