// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package so.service3;

public final class Service3Impl {
  private Service3Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_CreateWhiteboardRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_CreateWhiteboardRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_CreateWhiteboardResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_CreateWhiteboardResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_AddContentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_AddContentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_AddContentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_AddContentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_WhiteboardUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_WhiteboardUpdate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service3.proto\022\010service3\"0\n\027CreateWhit" +
      "eboardRequest\022\025\n\rnewWhiteboard\030\001 \001(\t\"2\n\030" +
      "CreateWhiteboardResponse\022\026\n\016whiteboardNa" +
      "me\030\001 \001(\t\"?\n\021AddContentRequest\022\026\n\016whitebo" +
      "ardName\030\001 \001(\t\022\022\n\naddContent\030\002 \001(\t\"2\n\022Add" +
      "ContentResponse\022\034\n\024newWhiteboardContent\030" +
      "\001 \001(\t\";\n\020WhiteboardUpdate\022\026\n\016whiteboardN" +
      "ame\030\001 \001(\t\022\017\n\007content\030\002 \001(\t2o\n\022Whiteboard" +
      "Creation\022Y\n\020CreateWhiteboard\022!.service3." +
      "CreateWhiteboardRequest\032\".service3.Creat" +
      "eWhiteboardResponse2\\\n\021WhiteboardContent" +
      "\022G\n\nAddContent\022\033.service3.AddContentRequ" +
      "est\032\034.service3.AddContentResponse2b\n\020Whi" +
      "teboardStream\022N\n\020WhiteboardStream\022\032.serv" +
      "ice3.WhiteboardUpdate\032\032.service3.Whitebo" +
      "ardUpdate(\0010\001B\035\n\013so.service3B\014Service3Im" +
      "plP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service3_CreateWhiteboardRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service3_CreateWhiteboardRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_CreateWhiteboardRequest_descriptor,
        new java.lang.String[] { "NewWhiteboard", });
    internal_static_service3_CreateWhiteboardResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service3_CreateWhiteboardResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_CreateWhiteboardResponse_descriptor,
        new java.lang.String[] { "WhiteboardName", });
    internal_static_service3_AddContentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service3_AddContentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_AddContentRequest_descriptor,
        new java.lang.String[] { "WhiteboardName", "AddContent", });
    internal_static_service3_AddContentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service3_AddContentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_AddContentResponse_descriptor,
        new java.lang.String[] { "NewWhiteboardContent", });
    internal_static_service3_WhiteboardUpdate_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_service3_WhiteboardUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_WhiteboardUpdate_descriptor,
        new java.lang.String[] { "WhiteboardName", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
