// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package so.service3;

public interface WhiteboardUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.WhiteboardUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *Name of the whiteboard
   * </pre>
   *
   * <code>string whiteboardName = 1;</code>
   */
  java.lang.String getWhiteboardName();
  /**
   * <pre>
   *Name of the whiteboard
   * </pre>
   *
   * <code>string whiteboardName = 1;</code>
   */
  com.google.protobuf.ByteString
      getWhiteboardNameBytes();

  /**
   * <pre>
   *Content update
   * </pre>
   *
   * <code>string content = 2;</code>
   */
  java.lang.String getContent();
  /**
   * <pre>
   *Content update
   * </pre>
   *
   * <code>string content = 2;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
