// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package so.service2;

public interface AlarmRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.AlarmRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *"startAlarm" or "stopAlarm"
   * </pre>
   *
   * <code>string operationType = 1;</code>
   */
  java.lang.String getOperationType();
  /**
   * <pre>
   *"startAlarm" or "stopAlarm"
   * </pre>
   *
   * <code>string operationType = 1;</code>
   */
  com.google.protobuf.ByteString
      getOperationTypeBytes();

  /**
   * <pre>
   *Alarm number to start or stop
   * </pre>
   *
   * <code>int32 alarmNumber = 2;</code>
   */
  int getAlarmNumber();
}
