// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package so.service2;

/**
 * Protobuf type {@code service2.AlarmResponse}
 */
public  final class AlarmResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:service2.AlarmResponse)
    AlarmResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AlarmResponse.newBuilder() to construct.
  private AlarmResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AlarmResponse() {
    currentAlarmState_ = "";
    newAlarmState_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AlarmResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            currentAlarmState_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            newAlarmState_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return so.service2.Service2Impl.internal_static_service2_AlarmResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return so.service2.Service2Impl.internal_static_service2_AlarmResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            so.service2.AlarmResponse.class, so.service2.AlarmResponse.Builder.class);
  }

  public static final int CURRENTALARMSTATE_FIELD_NUMBER = 1;
  private volatile java.lang.Object currentAlarmState_;
  /**
   * <pre>
   *Current alarm state
   * </pre>
   *
   * <code>string currentAlarmState = 1;</code>
   */
  public java.lang.String getCurrentAlarmState() {
    java.lang.Object ref = currentAlarmState_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      currentAlarmState_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *Current alarm state
   * </pre>
   *
   * <code>string currentAlarmState = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCurrentAlarmStateBytes() {
    java.lang.Object ref = currentAlarmState_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      currentAlarmState_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NEWALARMSTATE_FIELD_NUMBER = 2;
  private volatile java.lang.Object newAlarmState_;
  /**
   * <pre>
   *New state of alarm after the operation
   * </pre>
   *
   * <code>string newAlarmState = 2;</code>
   */
  public java.lang.String getNewAlarmState() {
    java.lang.Object ref = newAlarmState_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      newAlarmState_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *New state of alarm after the operation
   * </pre>
   *
   * <code>string newAlarmState = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNewAlarmStateBytes() {
    java.lang.Object ref = newAlarmState_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      newAlarmState_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCurrentAlarmStateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, currentAlarmState_);
    }
    if (!getNewAlarmStateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, newAlarmState_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCurrentAlarmStateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, currentAlarmState_);
    }
    if (!getNewAlarmStateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, newAlarmState_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof so.service2.AlarmResponse)) {
      return super.equals(obj);
    }
    so.service2.AlarmResponse other = (so.service2.AlarmResponse) obj;

    boolean result = true;
    result = result && getCurrentAlarmState()
        .equals(other.getCurrentAlarmState());
    result = result && getNewAlarmState()
        .equals(other.getNewAlarmState());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CURRENTALARMSTATE_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentAlarmState().hashCode();
    hash = (37 * hash) + NEWALARMSTATE_FIELD_NUMBER;
    hash = (53 * hash) + getNewAlarmState().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static so.service2.AlarmResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static so.service2.AlarmResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static so.service2.AlarmResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static so.service2.AlarmResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static so.service2.AlarmResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static so.service2.AlarmResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static so.service2.AlarmResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static so.service2.AlarmResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static so.service2.AlarmResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static so.service2.AlarmResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static so.service2.AlarmResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static so.service2.AlarmResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(so.service2.AlarmResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code service2.AlarmResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:service2.AlarmResponse)
      so.service2.AlarmResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return so.service2.Service2Impl.internal_static_service2_AlarmResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return so.service2.Service2Impl.internal_static_service2_AlarmResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              so.service2.AlarmResponse.class, so.service2.AlarmResponse.Builder.class);
    }

    // Construct using so.service2.AlarmResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      currentAlarmState_ = "";

      newAlarmState_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return so.service2.Service2Impl.internal_static_service2_AlarmResponse_descriptor;
    }

    @java.lang.Override
    public so.service2.AlarmResponse getDefaultInstanceForType() {
      return so.service2.AlarmResponse.getDefaultInstance();
    }

    @java.lang.Override
    public so.service2.AlarmResponse build() {
      so.service2.AlarmResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public so.service2.AlarmResponse buildPartial() {
      so.service2.AlarmResponse result = new so.service2.AlarmResponse(this);
      result.currentAlarmState_ = currentAlarmState_;
      result.newAlarmState_ = newAlarmState_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof so.service2.AlarmResponse) {
        return mergeFrom((so.service2.AlarmResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(so.service2.AlarmResponse other) {
      if (other == so.service2.AlarmResponse.getDefaultInstance()) return this;
      if (!other.getCurrentAlarmState().isEmpty()) {
        currentAlarmState_ = other.currentAlarmState_;
        onChanged();
      }
      if (!other.getNewAlarmState().isEmpty()) {
        newAlarmState_ = other.newAlarmState_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      so.service2.AlarmResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (so.service2.AlarmResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object currentAlarmState_ = "";
    /**
     * <pre>
     *Current alarm state
     * </pre>
     *
     * <code>string currentAlarmState = 1;</code>
     */
    public java.lang.String getCurrentAlarmState() {
      java.lang.Object ref = currentAlarmState_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currentAlarmState_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *Current alarm state
     * </pre>
     *
     * <code>string currentAlarmState = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCurrentAlarmStateBytes() {
      java.lang.Object ref = currentAlarmState_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentAlarmState_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *Current alarm state
     * </pre>
     *
     * <code>string currentAlarmState = 1;</code>
     */
    public Builder setCurrentAlarmState(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      currentAlarmState_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Current alarm state
     * </pre>
     *
     * <code>string currentAlarmState = 1;</code>
     */
    public Builder clearCurrentAlarmState() {
      
      currentAlarmState_ = getDefaultInstance().getCurrentAlarmState();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Current alarm state
     * </pre>
     *
     * <code>string currentAlarmState = 1;</code>
     */
    public Builder setCurrentAlarmStateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      currentAlarmState_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object newAlarmState_ = "";
    /**
     * <pre>
     *New state of alarm after the operation
     * </pre>
     *
     * <code>string newAlarmState = 2;</code>
     */
    public java.lang.String getNewAlarmState() {
      java.lang.Object ref = newAlarmState_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        newAlarmState_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *New state of alarm after the operation
     * </pre>
     *
     * <code>string newAlarmState = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNewAlarmStateBytes() {
      java.lang.Object ref = newAlarmState_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        newAlarmState_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *New state of alarm after the operation
     * </pre>
     *
     * <code>string newAlarmState = 2;</code>
     */
    public Builder setNewAlarmState(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      newAlarmState_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *New state of alarm after the operation
     * </pre>
     *
     * <code>string newAlarmState = 2;</code>
     */
    public Builder clearNewAlarmState() {
      
      newAlarmState_ = getDefaultInstance().getNewAlarmState();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *New state of alarm after the operation
     * </pre>
     *
     * <code>string newAlarmState = 2;</code>
     */
    public Builder setNewAlarmStateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      newAlarmState_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:service2.AlarmResponse)
  }

  // @@protoc_insertion_point(class_scope:service2.AlarmResponse)
  private static final so.service2.AlarmResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new so.service2.AlarmResponse();
  }

  public static so.service2.AlarmResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AlarmResponse>
      PARSER = new com.google.protobuf.AbstractParser<AlarmResponse>() {
    @java.lang.Override
    public AlarmResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AlarmResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AlarmResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AlarmResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public so.service2.AlarmResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

