// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package so.service2;

public interface CameraRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.CameraRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *Camera ID to monitor
   * </pre>
   *
   * <code>int32 monitorCamera = 1;</code>
   */
  int getMonitorCamera();
}
