// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package so.service2;

public interface CameraFeedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.CameraFeed)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *Live video feed (bytes stream)
   * </pre>
   *
   * <code>bytes cameraFeed = 1;</code>
   */
  com.google.protobuf.ByteString getCameraFeed();
}
