// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package so.service2;

public interface DoorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.DoorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *Current state, locked or unlocked
   * </pre>
   *
   * <code>string currentDoorState = 1;</code>
   */
  java.lang.String getCurrentDoorState();
  /**
   * <pre>
   *Current state, locked or unlocked
   * </pre>
   *
   * <code>string currentDoorState = 1;</code>
   */
  com.google.protobuf.ByteString
      getCurrentDoorStateBytes();

  /**
   * <pre>
   *New state of the door after the operation
   * </pre>
   *
   * <code>string newDoorState = 2;</code>
   */
  java.lang.String getNewDoorState();
  /**
   * <pre>
   *New state of the door after the operation
   * </pre>
   *
   * <code>string newDoorState = 2;</code>
   */
  com.google.protobuf.ByteString
      getNewDoorStateBytes();
}
