// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package so.service2;

/**
 * Protobuf type {@code service2.DoorResponse}
 */
public  final class DoorResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:service2.DoorResponse)
    DoorResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DoorResponse.newBuilder() to construct.
  private DoorResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DoorResponse() {
    currentDoorState_ = "";
    newDoorState_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DoorResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            currentDoorState_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            newDoorState_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return so.service2.Service2Impl.internal_static_service2_DoorResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return so.service2.Service2Impl.internal_static_service2_DoorResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            so.service2.DoorResponse.class, so.service2.DoorResponse.Builder.class);
  }

  public static final int CURRENTDOORSTATE_FIELD_NUMBER = 1;
  private volatile java.lang.Object currentDoorState_;
  /**
   * <pre>
   *Current state, locked or unlocked
   * </pre>
   *
   * <code>string currentDoorState = 1;</code>
   */
  public java.lang.String getCurrentDoorState() {
    java.lang.Object ref = currentDoorState_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      currentDoorState_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *Current state, locked or unlocked
   * </pre>
   *
   * <code>string currentDoorState = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCurrentDoorStateBytes() {
    java.lang.Object ref = currentDoorState_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      currentDoorState_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NEWDOORSTATE_FIELD_NUMBER = 2;
  private volatile java.lang.Object newDoorState_;
  /**
   * <pre>
   *New state of the door after the operation
   * </pre>
   *
   * <code>string newDoorState = 2;</code>
   */
  public java.lang.String getNewDoorState() {
    java.lang.Object ref = newDoorState_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      newDoorState_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *New state of the door after the operation
   * </pre>
   *
   * <code>string newDoorState = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNewDoorStateBytes() {
    java.lang.Object ref = newDoorState_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      newDoorState_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCurrentDoorStateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, currentDoorState_);
    }
    if (!getNewDoorStateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, newDoorState_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCurrentDoorStateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, currentDoorState_);
    }
    if (!getNewDoorStateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, newDoorState_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof so.service2.DoorResponse)) {
      return super.equals(obj);
    }
    so.service2.DoorResponse other = (so.service2.DoorResponse) obj;

    boolean result = true;
    result = result && getCurrentDoorState()
        .equals(other.getCurrentDoorState());
    result = result && getNewDoorState()
        .equals(other.getNewDoorState());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CURRENTDOORSTATE_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentDoorState().hashCode();
    hash = (37 * hash) + NEWDOORSTATE_FIELD_NUMBER;
    hash = (53 * hash) + getNewDoorState().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static so.service2.DoorResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static so.service2.DoorResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static so.service2.DoorResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static so.service2.DoorResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static so.service2.DoorResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static so.service2.DoorResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static so.service2.DoorResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static so.service2.DoorResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static so.service2.DoorResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static so.service2.DoorResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static so.service2.DoorResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static so.service2.DoorResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(so.service2.DoorResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code service2.DoorResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:service2.DoorResponse)
      so.service2.DoorResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return so.service2.Service2Impl.internal_static_service2_DoorResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return so.service2.Service2Impl.internal_static_service2_DoorResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              so.service2.DoorResponse.class, so.service2.DoorResponse.Builder.class);
    }

    // Construct using so.service2.DoorResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      currentDoorState_ = "";

      newDoorState_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return so.service2.Service2Impl.internal_static_service2_DoorResponse_descriptor;
    }

    @java.lang.Override
    public so.service2.DoorResponse getDefaultInstanceForType() {
      return so.service2.DoorResponse.getDefaultInstance();
    }

    @java.lang.Override
    public so.service2.DoorResponse build() {
      so.service2.DoorResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public so.service2.DoorResponse buildPartial() {
      so.service2.DoorResponse result = new so.service2.DoorResponse(this);
      result.currentDoorState_ = currentDoorState_;
      result.newDoorState_ = newDoorState_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof so.service2.DoorResponse) {
        return mergeFrom((so.service2.DoorResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(so.service2.DoorResponse other) {
      if (other == so.service2.DoorResponse.getDefaultInstance()) return this;
      if (!other.getCurrentDoorState().isEmpty()) {
        currentDoorState_ = other.currentDoorState_;
        onChanged();
      }
      if (!other.getNewDoorState().isEmpty()) {
        newDoorState_ = other.newDoorState_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      so.service2.DoorResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (so.service2.DoorResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object currentDoorState_ = "";
    /**
     * <pre>
     *Current state, locked or unlocked
     * </pre>
     *
     * <code>string currentDoorState = 1;</code>
     */
    public java.lang.String getCurrentDoorState() {
      java.lang.Object ref = currentDoorState_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currentDoorState_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *Current state, locked or unlocked
     * </pre>
     *
     * <code>string currentDoorState = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCurrentDoorStateBytes() {
      java.lang.Object ref = currentDoorState_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentDoorState_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *Current state, locked or unlocked
     * </pre>
     *
     * <code>string currentDoorState = 1;</code>
     */
    public Builder setCurrentDoorState(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      currentDoorState_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Current state, locked or unlocked
     * </pre>
     *
     * <code>string currentDoorState = 1;</code>
     */
    public Builder clearCurrentDoorState() {
      
      currentDoorState_ = getDefaultInstance().getCurrentDoorState();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Current state, locked or unlocked
     * </pre>
     *
     * <code>string currentDoorState = 1;</code>
     */
    public Builder setCurrentDoorStateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      currentDoorState_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object newDoorState_ = "";
    /**
     * <pre>
     *New state of the door after the operation
     * </pre>
     *
     * <code>string newDoorState = 2;</code>
     */
    public java.lang.String getNewDoorState() {
      java.lang.Object ref = newDoorState_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        newDoorState_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *New state of the door after the operation
     * </pre>
     *
     * <code>string newDoorState = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNewDoorStateBytes() {
      java.lang.Object ref = newDoorState_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        newDoorState_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *New state of the door after the operation
     * </pre>
     *
     * <code>string newDoorState = 2;</code>
     */
    public Builder setNewDoorState(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      newDoorState_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *New state of the door after the operation
     * </pre>
     *
     * <code>string newDoorState = 2;</code>
     */
    public Builder clearNewDoorState() {
      
      newDoorState_ = getDefaultInstance().getNewDoorState();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *New state of the door after the operation
     * </pre>
     *
     * <code>string newDoorState = 2;</code>
     */
    public Builder setNewDoorStateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      newDoorState_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:service2.DoorResponse)
  }

  // @@protoc_insertion_point(class_scope:service2.DoorResponse)
  private static final so.service2.DoorResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new so.service2.DoorResponse();
  }

  public static so.service2.DoorResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DoorResponse>
      PARSER = new com.google.protobuf.AbstractParser<DoorResponse>() {
    @java.lang.Override
    public DoorResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DoorResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DoorResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DoorResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public so.service2.DoorResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

