// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package so.service2;

public final class Service2Impl {
  private Service2Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_CameraRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_CameraRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_CameraFeed_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_CameraFeed_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_DoorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_DoorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_DoorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_DoorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_AlarmRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_AlarmRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_AlarmResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_AlarmResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service2.proto\022\010service2\"&\n\rCameraRequ" +
      "est\022\025\n\rmonitorCamera\030\001 \001(\005\" \n\nCameraFeed" +
      "\022\022\n\ncameraFeed\030\001 \001(\014\"8\n\013DoorRequest\022\025\n\ro" +
      "perationType\030\001 \001(\t\022\022\n\ndoorNumber\030\002 \001(\005\">" +
      "\n\014DoorResponse\022\030\n\020currentDoorState\030\001 \001(\t" +
      "\022\024\n\014newDoorState\030\002 \001(\t\":\n\014AlarmRequest\022\025" +
      "\n\roperationType\030\001 \001(\t\022\023\n\013alarmNumber\030\002 \001" +
      "(\005\"A\n\rAlarmResponse\022\031\n\021currentAlarmState" +
      "\030\001 \001(\t\022\025\n\rnewAlarmState\030\002 \001(\t2Q\n\rCameraC" +
      "ontrol\022@\n\rMonitorCamera\022\027.service2.Camer" +
      "aRequest\032\024.service2.CameraFeed0\0012K\n\013Door" +
      "Control\022<\n\013ControlDoor\022\025.service2.DoorRe" +
      "quest\032\026.service2.DoorResponse2O\n\014AlarmCo" +
      "ntrol\022?\n\014ControlAlarm\022\026.service2.AlarmRe" +
      "quest\032\027.service2.AlarmResponseB\035\n\013so.ser" +
      "vice2B\014Service2ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service2_CameraRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service2_CameraRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_CameraRequest_descriptor,
        new java.lang.String[] { "MonitorCamera", });
    internal_static_service2_CameraFeed_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service2_CameraFeed_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_CameraFeed_descriptor,
        new java.lang.String[] { "CameraFeed", });
    internal_static_service2_DoorRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service2_DoorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_DoorRequest_descriptor,
        new java.lang.String[] { "OperationType", "DoorNumber", });
    internal_static_service2_DoorResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service2_DoorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_DoorResponse_descriptor,
        new java.lang.String[] { "CurrentDoorState", "NewDoorState", });
    internal_static_service2_AlarmRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_service2_AlarmRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_AlarmRequest_descriptor,
        new java.lang.String[] { "OperationType", "AlarmNumber", });
    internal_static_service2_AlarmResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_service2_AlarmResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_AlarmResponse_descriptor,
        new java.lang.String[] { "CurrentAlarmState", "NewAlarmState", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
